namespace: app
service:
  name: monitorpro
  port: 8080
  image:
    path: docker.io/bharathpantala/monitorpro
    tag: "v2021.12"

ingress:
  host: monitorpro.cloudrural.com
  path: "/monitorpro"

#environments:

health:
  endpoint: /actuator/health
  livenessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 15
    periodSeconds: 30
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 15
    periodSeconds: 30
    failureThreshold: 10