apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitorpro
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: monitorpro
  endpoints:
  - port: api
    path: '/actuator/prometheus'
    interval: 10s
    honorLabels: true
