apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Values.service.name }}
    meta.helm.sh/release-namespace:  {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Values.service.name }}
    app.kubernetes.io/name: {{ .Values.service.name }}
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}